/* Esther's Light MVP — private browser-only student ministry experience. */
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const store={get:(k,f)=>{try{return JSON.parse(localStorage.getItem('el-'+k))??f}catch{return f}},set:(k,v)=>localStorage.setItem('el-'+k,JSON.stringify(v))};
const state={profile:store.get('profile',null),progress:store.get('progress',{chapters:0,studies:0,prayers:0,service:0,completedDays:[]}),journal:store.get('journal',[]),saved:store.get('saved',[]),lastRead:store.get('lastRead',{book:'John',chapter:1}),font:store.get('font',20),dark:store.get('dark',false),selectedVerse:''};
const needs=['I want to know God better','I am completely new to the Bible','I need help learning how to pray','I am anxious or overwhelmed','I am struggling with school','I feel like giving up','I feel far away from God','I need help finding my purpose','I am experiencing financial stress','I want to become a godly leader','I want healthier relationships','I am struggling with temptation','I need discipline and consistency','I want to read the entire Bible'];
const times=['5 minutes','10 minutes','15 minutes','30 minutes or more'],styles=['Reading','Journaling','Reflection questions','Quizzes','Prayer','A combination'],experiences=['Completely new','Some experience','Comfortable','Ready for deeper study'],audiences=['Young man','Young woman','Prefer not to answer','Show me resources for everyone'];
const chapters={
  John:{name:'John',testament:'New Testament',chapters:{1:[['1','In the beginning was the Word, and the Word was with God, and the Word was God.'],['2','The same was in the beginning with God.'],['3','All things were made through him. Without him, nothing was made that has been made.'],['4','In him was life, and the life was the light of men.'],['5','The light shines in the darkness, and the darkness has not overcome it.'],['14','The Word became flesh and lived among us. We saw his glory, glory as of the only Son of the Father, full of grace and truth.']],3:[['16','For God so loved the world, that he gave his only born Son, that whoever believes in him should not perish, but have eternal life.'],['17','For God didn’t send his Son into the world to judge the world, but that the world should be saved through him.']]}},
  Psalms:{name:'Psalms',testament:'Old Testament',chapters:{23:[['1','Yahweh is my shepherd: I shall lack nothing.'],['2','He makes me lie down in green pastures. He leads me beside still waters.'],['3','He restores my soul. He guides me in the paths of righteousness for his name’s sake.'],['4','Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me.']],27:[['1','Yahweh is my light and my salvation. Whom shall I fear? Yahweh is the strength of my life. Of whom shall I be afraid?']]}},
  Proverbs:{name:'Proverbs',testament:'Old Testament',chapters:{3:[['5','Trust in Yahweh with all your heart, and don’t lean on your own understanding.'],['6','In all your ways acknowledge him, and he will make your paths straight.']] }},
  Philippians:{name:'Philippians',testament:'New Testament',chapters:{4:[['6','In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God.'],['7','The peace of God, which passes all understanding, will guard your hearts and your thoughts in Christ Jesus.'],['13','I can do all things through Christ, who strengthens me.']] }},
  James:{name:'James',testament:'New Testament',chapters:{1:[['5','But if any of you lacks wisdom, let him ask of God, who gives to all liberally and without reproach; and it will be given to him.'],['22','But be doers of the word, and not only hearers, deluding your own selves.']] }},
  Esther:{name:'Esther',testament:'Old Testament',chapters:{4:[['14','Who knows if you haven’t come to the kingdom for such a time as this?']] }},
  Romans:{name:'Romans',testament:'New Testament',chapters:{8:[['1','There is therefore now no condemnation to those who are in Christ Jesus.'],['28','We know that all things work together for good for those who love God, to those who are called according to his purpose.']] }},
  Genesis:{name:'Genesis',testament:'Old Testament',chapters:{1:[['1','In the beginning, God created the heavens and the earth.'],['27','God created man in his own image. In God’s image he created him; male and female he created them.']] }}
};
const bibleBooks=[
  ['Genesis',50],['Exodus',40],['Leviticus',27],['Numbers',36],['Deuteronomy',34],['Joshua',24],['Judges',21],['Ruth',4],['1 Samuel',31],['2 Samuel',24],['1 Kings',22],['2 Kings',25],['1 Chronicles',29],['2 Chronicles',36],['Ezra',10],['Nehemiah',13],['Esther',10],['Job',42],['Psalms',150],['Proverbs',31],['Ecclesiastes',12],['Song of Solomon',8],['Isaiah',66],['Jeremiah',52],['Lamentations',5],['Ezekiel',48],['Daniel',12],['Hosea',14],['Joel',3],['Amos',9],['Obadiah',1],['Jonah',4],['Micah',7],['Nahum',3],['Habakkuk',3],['Zephaniah',3],['Haggai',2],['Zechariah',14],['Malachi',4],
  ['Matthew',28],['Mark',16],['Luke',24],['John',21],['Acts',28],['Romans',16],['1 Corinthians',16],['2 Corinthians',13],['Galatians',6],['Ephesians',6],['Philippians',4],['Colossians',4],['1 Thessalonians',5],['2 Thessalonians',3],['1 Timothy',6],['2 Timothy',4],['Titus',3],['Philemon',1],['Hebrews',13],['James',5],['1 Peter',5],['2 Peter',3],['1 John',5],['2 John',1],['3 John',1],['Jude',1],['Revelation',22]
];
const bibleBookIndex=Object.fromEntries(bibleBooks);
const chapterCache={};
const intros={Genesis:{author:'Traditionally attributed to Moses',setting:'Ancient Israel’s foundational story',purpose:'To reveal God as Creator and covenant-maker.',learn:'Your story begins with a God who creates with purpose.'},Psalms:{author:'A collection traditionally associated with David and other worshipers',setting:'Israel’s worship life across many seasons',purpose:'To give language for worship, grief, fear, gratitude, and trust.',learn:'You can bring your honest emotions to God.'},Proverbs:{author:'Traditionally associated with Solomon and other wise teachers',setting:'Ancient Israel’s wisdom tradition',purpose:'To form wise, God-honoring daily choices.',learn:'Wisdom can shape your studies, friendships, work, and decisions.'},Esther:{author:'The author is not named',setting:'The Persian Empire',purpose:'To show courage, providence, advocacy, and wise action.',learn:'Purpose can look like using your voice when people need you.'},John:{author:'Traditionally attributed to John',setting:'The first-century Mediterranean world',purpose:'To help readers believe that Jesus is the Son of God and receive life in his name.',learn:'Start with Jesus: his character, love, grace, and invitation.'},Romans:{author:'Traditionally attributed to Paul',setting:'A Christian community in first-century Rome',purpose:'To explain the good news of God’s grace and its impact on life.',learn:'Grace changes how you see failure, identity, and hope.'},Philippians:{author:'Traditionally attributed to Paul',setting:'A letter written while Paul was imprisoned',purpose:'To encourage joy, humility, partnership, and steady faith.',learn:'Joy and peace can be practiced in hard seasons.'},James:{author:'Traditionally attributed to James, a leader in the early church',setting:'Early Christian communities',purpose:'To show what lived-out faith looks like.',learn:'Faith can be visible in wise choices, courage, care, and action.'}};
const programs=[['First Light','Start Here','7 days','A first-week foundation in Scripture, prayer, grace, identity, and a daily walk with God.','first'],['For Such a Time as This','Purpose','14 days','A courage-and-purpose study through Esther for every student.','soon'],['Before You Give Up','Support','7 days','For academic, financial, emotional, and stay-enrolled pressure.','soon'],["God, I'm Tired",'Rest','7 days','A study on burnout, disappointment, rest, and dependence on God.','soon'],['Faith After Failure','Starting Over','7 days','For a failed class, lost opportunity, change of plans, or feeling behind.','soon'],['The Godly Leader','Leadership','7 days','Servant leadership, integrity, humility, accountability, and influence.','soon'],['Men of Purpose','Optional path','7 days','Identity, discipline, emotional health, responsibility, brotherhood, and asking for help.','soon'],['Women of Purpose','Optional path','7 days','Wisdom, confidence, boundaries, friendship, healing, leadership, and purpose.','soon'],['Together in the Light','Community','7 days','Friendship, respect, communication, forgiveness, service, and support.','soon'],['The 66-Book Journey','Bible Plan','66 books','A structured journey through the Protestant Bible.','soon']];
const firstLight=[
 ['Day 1 · You are invited','John 1:4–5','In him was life, and the life was the light of men. The light shines in the darkness, and the darkness has not overcome it.','God does not ask you to have everything figured out before you come close. The first light of faith is not your performance—it is Christ meeting you where you are.','John opens by calling Jesus the light. This is Scripture, followed by reflection—not a promise that darkness is easy or instant.','What darkness or uncertainty feels most present today?','Where do you need to let God meet you as you are?','What would one small step toward light look like?','God, meet me in the part of my life that feels uncertain. Help me take one honest step toward you.','Set a five-minute reminder for tomorrow and return to this space.'],
 ['Day 2 · Grace before striving','Romans 8:1','There is therefore now no condemnation to those who are in Christ Jesus.','You may need accountability. You may need to repair something. But condemnation is not the voice that brings you home. Grace gives you room to tell the truth and begin again.','Romans 8 speaks into life in Christ. Christians may describe its theological implications in different ways; its opening assurance is clear.','What failure or shame keeps replaying in your mind?','How is grace different from pretending nothing happened?','What is one kind next step you can take today?','Jesus, help me receive your grace and walk in truth.','Write one sentence you would say to a friend who made the same mistake.'],
 ['Day 3 · Pray honestly','Philippians 4:6–7','In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God.','Prayer is not a test of impressive words. It is a place to bring the real request, the real fear, and the small gratitude you can name today.','Paul writes to a church facing pressure. This passage encourages prayer; it is not a replacement for counseling, medical care, or emergency support.','What do you need to name honestly to God?','What is one thing you can thank God for today?','Who can support you if anxiety is becoming too heavy to carry alone?','God, I bring you what I cannot control. Guard my heart and help me seek support when I need it.','Write a one-sentence prayer before checking your phone in the morning.'],
 ['Day 4 · Wisdom for the next step','James 1:5','But if any of you lacks wisdom, let him ask of God, who gives to all liberally and without reproach.','You do not need the full map to ask for wisdom about the next right decision. God is not irritated by your questions.','James connects wisdom with lived faith. The verse encourages asking, while wise decisions can also involve advisors, counselors, and practical information.','What decision is asking for wisdom right now?','What information or advice do you still need?','What is the next right—not perfect—step?','God, give me wisdom and courage to act on what is true.','Ask one trusted person a specific question about your next step.'],
 ['Day 5 · Trust in the process','Proverbs 3:5–6','Trust in Yahweh with all your heart, and don’t lean on your own understanding. In all your ways acknowledge him, and he will make your paths straight.','Trust is not shutting off your mind. It is refusing to make your limited view the only voice in the room. Bring your plans, questions, and work to God.','Proverbs is wisdom literature. “Straight paths” should not be read as a guarantee of an easy life.','Where are you relying only on your own understanding?','How can faith and practical planning work together?','What plan can you place before God today?','God, guide my steps and help me be teachable.','Make a simple two-column list: what I can do / what I need to release.'],
 ['Day 6 · You belong','Genesis 1:27','God created man in his own image. In God’s image he created him; male and female he created them.','Your value does not rise and fall with your grades, relationship status, bank balance, or how together you feel. You bear God’s image.','Genesis presents humanity as created in God’s image. This study welcomes young men and young women without restricting any general resource.','What has been making you question your value?','What changes when you remember your worth is given, not earned?','How can you speak dignity over another student this week?','God, help me see myself and other people with dignity and care.','Send one specific encouragement to someone who may feel overlooked.'],
 ['Day 7 · Carry the light','Matthew 5:14–16','You are the light of the world. A city located on a hill can’t be hidden.','Faith becomes visible in ordinary faithfulness: telling the truth, asking for help, studying with integrity, serving, forgiving, and checking on people.','Jesus uses light as a picture of public goodness that points beyond ourselves to God.','Where can you carry light in your campus life?','What service or encouragement feels possible this week?','How can you do good without needing attention for it?','God, let my life bring care, courage, and hope to someone else.','Choose one Carry the Light service action below.']
];
const life=[['Anxiety','Philippians 4:6–7','Bring the real request to God, then choose one grounded next step and reach for support if anxiety is heavy.'],['Academic failure','Romans 8:1','A grade can be information—not your identity. Talk to an advisor, instructor, or support office.'],['Financial stress','Matthew 6:34','You do not have to carry money pressure alone. Make a 72-hour plan and connect to EFF or campus aid.'],['Feeling behind','Psalm 27:1','Your timeline is not proof of your worth. Choose the next faithful, practical step.'],['Burnout','Psalm 23:2–3','Rest is not quitting. Tell someone you are tired and make room for recovery.'],['Loneliness','Psalm 68:6','Connection can begin with one honest text, a campus group, or a trusted person.'],['Purpose','Esther 4:14','Purpose often grows through preparation, courage, and serving real people.'],['Starting over','Isaiah 43:19','New beginnings can be quiet. Ask what needs repair, support, and patient rebuilding.']];
const prayerTopics=['Pray for myself','Pray for my education','Pray for my family','Pray for a friend','Pray about a decision','Pray when I do not know what to say','Pray through anxiety','Confess and begin again','Thank God','Pray for my campus'];
function saveAll(){store.set('profile',state.profile);store.set('progress',state.progress);store.set('journal',state.journal);store.set('saved',state.saved);store.set('lastRead',state.lastRead);store.set('font',state.font);store.set('dark',state.dark)}
function choiceHtml(list,name,type='radio'){return list.map((v,i)=>`<span class="${type==='checkbox'?'choice':'radio'}"><input type="${type}" name="${name}" id="${name}${i}" value="${v}"><label for="${name}${i}">${v}</label></span>`).join('')}
function initAssessment(){ $('#needsChoices').innerHTML=choiceHtml(needs,'needs','checkbox');$('#timeChoices').innerHTML=choiceHtml(times,'time');$('#styleChoices').innerHTML=choiceHtml(styles,'style');$('#experienceChoices').innerHTML=choiceHtml(experiences,'experience');$('#audienceChoices').innerHTML=choiceHtml(audiences,'audience'); $('#assessmentForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);const selected=[...$$('input[name="needs"]:checked')].map(x=>x.value);state.profile={needs:selected,time:f.get('time')||'10 minutes',style:f.get('style')||'A combination',experience:f.get('experience')||'Completely new',audience:f.get('audience')||'Show me resources for everyone'};saveAll();renderDashboard();$('#my-light').scrollIntoView({behavior:'smooth'});});}
function recommendation(){let n=state.profile?.needs||[];if(n.some(x=>/anxious|giving up|far away/.test(x)))return ['Psalms','First Light','A gentle place to bring honest emotions to God.','Take a three-minute pause: breathe slowly, name what is true, and tell one trusted person how you are doing.'];if(n.some(x=>/school|financial/.test(x)))return ['James','Before You Give Up','Wisdom and practical next steps for a pressured season.','Write down the one academic or money task that needs help first, then contact the right person today.'];if(n.some(x=>/purpose|leader/.test(x)))return ['Esther','For Such a Time as This','Courage, preparation, and purpose for your influence.','Encourage one student or use your voice to help solve a real problem this week.'];if(n.some(x=>/Bible|God better|entire Bible/.test(x)))return ['John','First Light','A clear beginning with Jesus and the good news.','Read one short passage and write down one word or phrase you notice.'];return ['Philippians','First Light','A grounded start for faith in real student life.','Choose a five-minute window tomorrow and protect it as a meeting with God.'];}
function renderDashboard(){const p=state.profile;if(!p){$('#dashboardEmpty').hidden=false;$('#dashboardContent').hidden=true;return}$('#dashboardEmpty').hidden=true;$('#dashboardContent').hidden=false;const [book,program,reason,action]=recommendation();const daily=['Your word is a lamp to my feet and a light for my path.','Your word is a lamp to my feet and a light for my path.','God is our refuge and strength, a very present help in trouble.'][new Date().getDay()%3];$('#dailyVerse').textContent='“'+daily+'”';$('#dailyReference').textContent=daily.startsWith('God')?'Psalm 46:1 (WEB)':'Psalm 119:105 (WEB)';$('#planBook').textContent=`Start with ${book}`;$('#planReason').textContent=`${program}: ${reason}`;$('#planTime').textContent=p.time;$('#planStyle').textContent=p.style;$('#planActionTitle').textContent='Make it real';$('#planAction').textContent=action;renderProgress();}
function renderProgress(){let p=state.progress,total=p.chapters+p.studies+p.prayers+p.service;$('#chaptersCount').textContent=p.chapters;$('#studyCount').textContent=p.studies;$('#prayerCount').textContent=p.prayers;$('#serviceCount').textContent=p.service;$('#progressLabel').textContent=`${total} faithful step${total===1?'':'s'}`;$('#progressFill').style.width=Math.min(100,total*7)+'%'}
function initReader(){const books=Object.keys(chapters);$('#bookSelect').innerHTML=books.map(b=>`<option ${b===state.lastRead.book?'selected':''}>${b}</option>`).join('');$('#bookSelect').addEventListener('change',()=>{state.lastRead.book=$('#bookSelect').value;state.lastRead.chapter=Object.keys(chapters[state.lastRead.book].chapters)[0];renderChapter()});$('#chapterSelect').addEventListener('change',()=>{state.lastRead.chapter=+$('#chapterSelect').value;renderChapter()});$('#previousChapter').onclick=()=>moveChapter(-1);$('#nextChapter').onclick=()=>moveChapter(1);$('#bookmarkChapter').onclick=()=>saveVerse(`${state.lastRead.book} ${state.lastRead.chapter}`,`Chapter bookmark`,true);$('#copyChapter').onclick=()=>navigator.clipboard?.writeText($('#scriptureText').innerText);$('#printChapter').onclick=()=>window.print();$('#continueReading').onclick=renderChapter;$('#fontUp').onclick=()=>{state.font=Math.min(30,state.font+2);renderChapter()};$('#fontDown').onclick=()=>{state.font=Math.max(16,state.font-2);renderChapter()};$('#themeToggle').onclick=()=>{state.dark=!state.dark;$('#readerPaper').classList.toggle('reader-dark',state.dark);saveAll()};$('#sendToSoap').onclick=()=>{if(state.selectedVerse)$('#soapScripture').value=state.selectedVerse;$('#soap').scrollIntoView({behavior:'smooth'})};$('#openIntro').onclick=openIntro;renderChapter();}
function renderChapter(){let b=state.lastRead.book,chs=Object.keys(chapters[b].chapters);$('#chapterSelect').innerHTML=chs.map(c=>`<option value="${c}" ${+c===+state.lastRead.chapter?'selected':''}>${c}</option>`).join('');let verses=chapters[b].chapters[state.lastRead.chapter];$('#chapterHeading').textContent=`${b} ${state.lastRead.chapter}`;$('#scriptureText').style.fontSize=state.font+'px';$('#readerPaper').classList.toggle('reader-dark',state.dark);$('#scriptureText').innerHTML=verses.map(([num,text])=>`<span class="verse" tabindex="0" data-verse="${b} ${state.lastRead.chapter}:${num} — ${text}"><sup>${num}</sup>${text}</span>`).join('');$$('.verse').forEach(v=>v.addEventListener('click',()=>{state.selectedVerse=v.dataset.verse;$$('.verse').forEach(x=>x.classList.remove('selected'));v.classList.add('selected')}));state.progress.chapters=Math.max(state.progress.chapters,1);saveAll();renderProgress();renderSaved();}
function moveChapter(dir){let b=state.lastRead.book,a=Object.keys(chapters[b].chapters).map(Number),i=a.indexOf(+state.lastRead.chapter);i=Math.max(0,Math.min(a.length-1,i+dir));state.lastRead.chapter=a[i];renderChapter()}
function saveVerse(title,body,chapter=false){if(state.saved.some(x=>x.title===title))return;let v={id:crypto.randomUUID(),type:'verse',title,body,date:new Date().toISOString(),chapter};state.saved.unshift(v);state.journal.unshift(v);saveAll();renderSaved();renderJournal();}
function renderSaved(){$('#savedVerses').innerHTML=state.saved.slice(0,4).map(v=>`<div class="saved-verse"><strong>${v.title}</strong><br>${v.body.slice(0,70)}${v.body.length>70?'…':''}</div>`).join('')||'<p>No saved verses yet.</p>'}
function openIntro(){let name=state.lastRead.book,i=intros[name]||{author:'Introduction coming soon',setting:'',purpose:'',learn:''};$('#bookIntro').innerHTML=`<p class="eyebrow">${chapters[name].testament.toUpperCase()}</p><h2>${name}</h2><p><strong>Authorship:</strong> ${i.author}</p><p><strong>Historical setting:</strong> ${i.setting}</p><p><strong>Purpose:</strong> ${i.purpose}</p><p><strong>For students:</strong> ${i.learn}</p><p><strong>Before you read:</strong> What do I want to notice about God, people, and my own season?</p>`;$('#bookDialog').showModal()}
function initPrograms(){let cats=['All','Start Here','Purpose','Support','Rest','Leadership','Community','Bible Plan'];$('#studyFilters').innerHTML=cats.map((c,i)=>`<button class="${i===0?'active':''}" data-filter="${c}">${c}</button>`).join('');$$('#studyFilters button').forEach(b=>b.onclick=()=>{ $$('#studyFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPrograms(b.dataset.filter)});renderPrograms('All');$('#previousDay').onclick=()=>renderDay(currentDay-1);$('#nextDay').onclick=()=>renderDay(currentDay+1);$('#completeDay').onclick=completeDay;}
function renderPrograms(filter){$('#programGrid').innerHTML=programs.filter(p=>filter==='All'||p[1]===filter).map(p=>`<article class="program-card"><span class="tag">${p[1]}</span><h3>${p[0]}</h3><p>${p[3]}</p><p class="reference">${p[2]} · ${p[4]==='soon'?'COMING SOON':'READY NOW'}</p><button class="button ${p[4]==='first'?'button-solid':'button-outline'} small" ${p[4]==='first'?'data-first-light':''}>${p[4]==='first'?'Open First Light':'Explore the pathway'}</button></article>`).join('');const first=$('[data-first-light]');if(first)first.onclick=()=>{ $('#firstLight').hidden=false;renderDay(0);$('#firstLight').scrollIntoView({behavior:'smooth'})}}
let currentDay=0;function renderDay(n){currentDay=Math.max(0,Math.min(firstLight.length-1,n));let d=firstLight[currentDay];$('#dayTitle').textContent=d[0];$('#dayReference').textContent=d[1];$('#dayScripture').textContent='“'+d[2]+'”';$('#dayDevotional').textContent=d[3];$('#dayContext').textContent=d[4];$('#dayQuestions').innerHTML=[d[5],d[6],d[7]].map(x=>`<li>${x}</li>`).join('');$('#dayPrayer').textContent=d[8];$('#dayAction').textContent=d[9];$('#dayProgress').textContent=`Day ${currentDay+1} of 7`;$('#dayJournal').value=store.get('day-'+currentDay,'');$('#dayJournal').oninput=e=>store.set('day-'+currentDay,e.target.value);$('#previousDay').disabled=currentDay===0;$('#nextDay').disabled=currentDay===6;$('#completeDay').textContent=state.progress.completedDays.includes(currentDay)?'Completed ✓':'Mark Complete';}
function completeDay(){if(!state.progress.completedDays.includes(currentDay)){state.progress.completedDays.push(currentDay);state.progress.studies++;state.journal.unshift({id:crypto.randomUUID(),type:'study',title:firstLight[currentDay][0],body:$('#dayJournal').value||'First Light day completed.',date:new Date().toISOString()});saveAll();renderProgress();renderJournal()}renderDay(currentDay)}
function initLife(){$('#lifeGrid').innerHTML=life.map(x=>`<article class="life-card"><h3>${x[0]}</h3><p class="reference">${x[1]}</p><p>${x[2]}</p></article>`).join('')}
function initPrayer(){let active='';$('#prayerTopics').innerHTML=prayerTopics.map(t=>`<button type="button">${t}</button>`).join('');$$('#prayerTopics button').forEach(b=>b.onclick=()=>{active=b.textContent;$$('#prayerTopics button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#prayerText').placeholder=`${active}: God, I bring you…`});$('#prayerForm').addEventListener('submit',e=>{e.preventDefault();let text=$('#prayerText').value.trim();if(!text)return;state.journal.unshift({id:crypto.randomUUID(),type:'prayer',title:active||'Private prayer',body:text,date:new Date().toISOString(),answered:$('#answeredPrayer').checked});state.progress.prayers++;$('#prayerText').value='';$('#answeredPrayer').checked=false;saveAll();renderProgress();renderJournal()});let seconds=300,timer;const show=()=>$('#timerValue').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;$('#timerStart').onclick=()=>{if(timer){clearInterval(timer);timer=null;$('#timerStart').textContent='Start timer';return}timer=setInterval(()=>{if(seconds<=0){clearInterval(timer);timer=null;$('#timerStart').textContent='Start timer';return}seconds--;show()},1000);$('#timerStart').textContent='Pause timer'};$('#timerReset').onclick=()=>{clearInterval(timer);timer=null;seconds=300;show();$('#timerStart').textContent='Start timer'};show()}
function initSoap(){$('#soapForm').addEventListener('submit',e=>{e.preventDefault();let f=['soapScripture','soapObservation','soapApplication','soapPrayer'].map(id=>$('#'+id).value.trim());if(!f.some(Boolean))return;state.journal.unshift({id:crypto.randomUUID(),type:'study',title:f[0]||'S.O.A.P. Study',body:`Observation: ${f[1]}\n\nApplication: ${f[2]}\n\nPrayer: ${f[3]}`,date:new Date().toISOString()});state.progress.studies++;e.target.reset();saveAll();renderProgress();renderJournal()})}
function renderJournal(filter='all'){$('#journalList').innerHTML=state.journal.filter(e=>filter==='all'||e.type===filter).map(e=>`<article class="journal-entry"><header><div><p class="eyebrow">${e.type.toUpperCase()}${e.answered?' · ANSWERED':''}</p><h3>${escapeHtml(e.title)}</h3></div><button class="text-button delete-entry" data-id="${e.id}">Delete</button></header><time>${new Date(e.date).toLocaleDateString()}</time><p>${escapeHtml(e.body)}</p></article>`).join('')||'<p>No entries here yet. What is one thing you want to remember?</p>';$$('.delete-entry').forEach(b=>b.onclick=()=>{if(confirm('Delete this private entry from this browser?')){state.journal=state.journal.filter(e=>e.id!==b.dataset.id);state.saved=state.saved.filter(e=>e.id!==b.dataset.id);saveAll();renderJournal(filter);renderSaved()}})}
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function initMore(){$('#startGame').onclick=()=>{let box=$('#gameBox');box.hidden=!box.hidden;box.innerHTML=`<strong>Put the verse in order</strong><p>Arrange the ideas in Psalm 119:105.</p><button data-game="Your word">Your word</button><button data-game="is a lamp">is a lamp</button><button data-game="to my feet">to my feet</button><p id="gameFeedback"></p>`;$$('[data-game]').forEach(b=>b.onclick=()=>{$('#gameFeedback').textContent='Good work. The full verse is: “Your word is a lamp to my feet and a light for my path.”';state.progress.studies++;saveAll();renderProgress()})};$('#serviceAction').onclick=()=>{let box=$('#serviceBox');box.hidden=!box.hidden;box.innerHTML=`<strong>Try this: Check on a student.</strong><p>Send one specific message: “I was thinking about you. How are you really doing this week?”</p><p><b>Time:</b> 5 minutes · <b>Safety:</b> If they share immediate danger, contact emergency support or 988 with them.</p><button id="serviceComplete">Mark complete</button>`;$('#serviceComplete').onclick=()=>{state.progress.service++;state.journal.unshift({id:crypto.randomUUID(),type:'service',title:'Carry the Light: checked on a student',body:'Completed a small act of student support.',date:new Date().toISOString()});saveAll();renderProgress();renderJournal();$('#serviceComplete').textContent='Completed ✓'}};$('#printCertificate').onclick=()=>{let name=$('#certificateName').value.trim()||'Student';let w=window.open('','_blank');w.document.write(`<title>Esther’s Light Certificate</title><style>body{font-family:Georgia;padding:70px;text-align:center;color:#32155c;border:18px solid #42127f;margin:20px}h1{font-size:56px;margin:35px 0 10px}p{font-size:20px;line-height:1.6}.gold{color:#a77a16}</style><p class="gold">ESTHER FUNDS FOUNDATION</p><h1>Certificate of Completion</h1><p>This recognizes</p><h2>${escapeHtml(name)}</h2><p>for completing <b>First Light</b><br>Esther’s Light · ${new Date().toLocaleDateString()}<br>Certificate No. EL-${Date.now().toString().slice(-8)}</p><p>Every Future Fulfilled</p><script>window.print()<\/script>`);w.document.close()}};
function initExport(){$('#exportData').onclick=()=>{let blob=new Blob([JSON.stringify({profile:state.profile,progress:state.progress,journal:state.journal,saved:state.saved,lastRead:state.lastRead},null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='esthers-light-private-backup.json';a.click();URL.revokeObjectURL(a.href)};$('#importData').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(!confirm('Replace this browser’s Esther’s Light private data with this backup?'))return;Object.assign(state,{profile:d.profile||null,progress:d.progress||state.progress,journal:d.journal||[],saved:d.saved||[],lastRead:d.lastRead||state.lastRead});saveAll();renderDashboard();renderJournal();renderSaved();renderProgress();alert('Backup restored.')}catch{alert('That file could not be read as an Esther’s Light backup.')}};r.readAsText(f)}}
function initReaderFullBible(){
  if(!bibleBookIndex[state.lastRead.book])state.lastRead={book:'John',chapter:1};
  const bookSelect=$('#bookSelect'),chapterSelect=$('#chapterSelect'),status=$('#readerStatus');
  bookSelect.innerHTML=bibleBooks.map(([book])=>`<option value="${book}" ${book===state.lastRead.book?'selected':''}>${book}</option>`).join('');
  const chaptersForBook=()=>{
    const count=bibleBookIndex[state.lastRead.book]||1;
    chapterSelect.innerHTML=Array.from({length:count},(_,index)=>`<option value="${index+1}" ${index+1===+state.lastRead.chapter?'selected':''}>${index+1}</option>`).join('');
  };
  const showChapter=async()=>{
    chaptersForBook();const book=state.lastRead.book,chapter=state.lastRead.chapter,key=`${book} ${chapter}`;
    $('#chapterHeading').textContent=key;$('#scriptureText').style.fontSize=state.font+'px';$('#readerPaper').classList.toggle('reader-dark',state.dark);
    $('#scriptureText').innerHTML='<p class="reader-loading">Opening Scripture…</p>';status.textContent='Opening chapter…';
    let verses=chapterCache[key];
    if(!verses){
      try{const response=await fetch(`https://bible-api.com/${encodeURIComponent(key)}?translation=web`);if(!response.ok)throw new Error('Unavailable');const data=await response.json();if(!Array.isArray(data.verses)||!data.verses.length)throw new Error('Missing chapter');verses=data.verses.map(verse=>[String(verse.verse),verse.text.trim()]);chapterCache[key]=verses;status.textContent='World English Bible (WEB)'}
      catch(error){verses=chapters[book]?.chapters?.[chapter]||[];status.textContent=verses.length?'Showing saved WEB reading sample':'This chapter needs an internet connection. Please try again.'}
    }else status.textContent='World English Bible (WEB)';
    if(book!==state.lastRead.book||chapter!==state.lastRead.chapter)return;
    $('#scriptureText').innerHTML=verses.length?verses.map(([number,text])=>`<span class="verse" tabindex="0" data-verse="${book} ${chapter}:${number} — ${text}"><sup>${number}</sup>${text}</span>`).join(''):'<p class="reader-loading">Please check your connection and open this chapter again.</p>';
    $$('.verse').forEach(verse=>verse.addEventListener('click',()=>{state.selectedVerse=verse.dataset.verse;$$('.verse').forEach(item=>item.classList.remove('selected'));verse.classList.add('selected')}));
    state.progress.chapters=Math.max(state.progress.chapters,1);saveAll();renderProgress();renderSaved();
  };
  const move=(direction)=>{let index=bibleBooks.findIndex(([name])=>name===state.lastRead.book),next=+state.lastRead.chapter+direction;if(next<1&&index>0){index--;state.lastRead.book=bibleBooks[index][0];next=bibleBooks[index][1]}if(next>bibleBooks[index][1]&&index<bibleBooks.length-1){index++;state.lastRead.book=bibleBooks[index][0];next=1}state.lastRead.chapter=next;bookSelect.value=state.lastRead.book;showChapter()};
  bookSelect.onchange=()=>{state.lastRead.book=bookSelect.value;state.lastRead.chapter=1;showChapter()};chapterSelect.onchange=()=>{state.lastRead.chapter=+chapterSelect.value;showChapter()};
  $('#previousChapter').onclick=()=>move(-1);$('#nextChapter').onclick=()=>move(1);$('#continueReading').onclick=showChapter;
  $('#bookmarkChapter').onclick=()=>saveVerse(`${state.lastRead.book} ${state.lastRead.chapter}`,'Chapter bookmark',true);$('#copyChapter').onclick=()=>navigator.clipboard?.writeText($('#scriptureText').innerText);$('#printChapter').onclick=()=>window.print();
  $('#fontUp').onclick=()=>{state.font=Math.min(30,state.font+2);showChapter()};$('#fontDown').onclick=()=>{state.font=Math.max(16,state.font-2);showChapter()};$('#themeToggle').onclick=()=>{state.dark=!state.dark;$('#readerPaper').classList.toggle('reader-dark',state.dark);saveAll()};
  $('#sendToSoap').onclick=()=>{if(state.selectedVerse)$('#soapScripture').value=state.selectedVerse;$('#soap').scrollIntoView({behavior:'smooth'})};
  $('#openIntro').onclick=()=>{const book=state.lastRead.book,info=intros[book];$('#bookIntro').innerHTML=`<p class="eyebrow">${book==='Psalms'?'OLD TESTAMENT':'BIBLE READER'}</p><h2>${book}</h2><p>${info?`<strong>Purpose:</strong> ${info.purpose}`:'Choose one chapter at a time. Read slowly, notice what stands out, and respond honestly to God.'}</p><p><strong>Reading practice:</strong> Ask: What do I notice about God? What is true here? What is one faithful next step?</p>`;$('#bookDialog').showModal()};
  showChapter();
}
function initNav(){$('#menuButton').onclick=()=>{let open=$('#siteNav').classList.toggle('open');$('#menuButton').setAttribute('aria-expanded',open)};document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#siteNav').classList.remove('open');$('#menuButton').setAttribute('aria-expanded','false')}});$$('[data-scroll]').forEach(b=>b.onclick=()=>$(b.dataset.scroll).scrollIntoView({behavior:'smooth'}));$('#copyDailyVerse').onclick=()=>navigator.clipboard?.writeText(`${$('#dailyVerse').textContent} ${$('#dailyReference').textContent}`);$('#resetProfile').onclick=()=>$('#assessment').scrollIntoView({behavior:'smooth'});$('#bookDialog .dialog-close').onclick=()=>$('#bookDialog').close();$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');renderJournal(t.dataset.journal)})}
initNav();initAssessment();initReaderFullBible();initPrograms();initLife();initPrayer();initSoap();initMore();initExport();renderDashboard();renderJournal();renderSaved();renderProgress();
